### ISSUE TITLE
Fatal Error building adv.go

### ISSUE THREAD

**Issue by Chillance** [aykevl/things#1]
Hi,

I thought it would be cool to try this out on my nrf52840-mdk and when I use the code in adv.go I get this:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x25cdbfe]

runtime stack:
runtime.throw(0x346e583, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0xbeb8a0, 0xc001f61608, 0xc001bba1b0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc001f615d8 sp=0xc001f615a0 pc=0x89ba2b
github.com/tinygo-org/tinygo/vendor/tinygo.org/x/go-llvm._Cfunc_LLVMTargetMachineEmitToMemoryBuffer(0x643e2c0, 0x6440670, 0xc000000001, 0xc001bba1a8, 0xc001bba1b0, 0xc000000000)
	_cgo_gotypes.go:8970 +0x4d fp=0xc001f61608 sp=0xc001f615d8 pc=0xa6c7fd
github.com/tinygo-org/tinygo/vendor/tinygo.org/x/go-llvm.TargetMachine.EmitToMemoryBuffer.func1(0x643e2c0, 0x6440670, 0x1, 0xc001bba1a8, 0xc001bba1b0, 0x0)
	/go/src/github.com/tinygo-org/tinygo/vendor/tinygo.org/x/go-llvm/target.go:274 +0x18b fp=0xc001f61648 sp=0xc001f61608 pc=0xa94adb
github.com/tinygo-org/tinygo/vendor/tinygo.org/x/go-llvm.TargetMachine.EmitToMemoryBuffer(0x643e2c0, 0x6440670, 0x1, 0xc0019c3cc0, 0x1b, 0x1)
	/go/src/github.com/tinygo-org/tinygo/vendor/tinygo.org/x/go-llvm/target.go:274 +0x84 fp=0xc001f616b0 sp=0xc001f61648 pc=0xa7a324
github.com/tinygo-org/tinygo/compiler.(*Compiler).EmitObject(0xc0000b0b00, 0xc0019c3cc0, 0x1b, 0xc0019c3cc0, 0x1b)
	/go/src/github.com/tinygo-org/tinygo/compiler/compiler.go:2768 +0x4a fp=0xc001f61700 sp=0xc001f616b0 pc=0xb8426a
main.Compile(0x7fff5c7ecf1c, 0xc, 0x7fff5c7ecee6, 0x14, 0xc0000b02c0, 0xc001f61f10, 0xc001f61da0, 0x0, 0x0)
	/go/src/github.com/tinygo-org/tinygo/main.go:176 +0x85d fp=0xc001f61d58 sp=0xc001f61700 pc=0xbd641d
main.Build(0x7fff5c7ecf1c, 0xc, 0x7fff5c7ecee6, 0x14, 0x7fff5c7ecf0f, 0xc, 0xc000083f10, 0xc000044630, 0x3d)
	/go/src/github.com/tinygo-org/tinygo/main.go:284 +0xe2 fp=0xc001f61dc8 sp=0xc001f61d58 pc=0xbd9132
main.main()
	/go/src/github.com/tinygo-org/tinygo/main.go:565 +0xbd5 fp=0xc001f61f98 sp=0xc001f61dc8 pc=0xbdac45
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc001f61fe0 sp=0xc001f61f98 pc=0x8c62ac
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001f61fe8 sp=0xc001f61fe0 pc=0x8f0971

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

I'm building this using tinygo docker version 0.5.0. If I change the code to this:

```
	//println("sd enabled:", sd.IsEnabled())
	//println("sd enable:", sd.Enable(sd.DefaultClockSource))
	//println("sd enabled:", sd.IsEnabled())
```
It goes through, and flashes, but I don't see the bluetooth device.

Any thoughts what is going on here?

Thanks!

**Comment by aykevl** [comment]
To be honest, that was just a quick thing I put together to test things out. It is not complete. I might or might not fix this at some point.
What I'm really working on now is better support for CGo so I can provide easy-to-use wrappers for the native C interface. I already have managed to get the SoftDevice to initialize so the rest should certainly be possible. I haven't pushed the code yet as it's not nearly ready.

**Comment by Chillance** [comment]
Oh, ok, it looked like it could work so I thought the error might have been something easy to fix, but if it's not and you got something better going, then even better.

**Comment by Chillance** [comment]
Any ETA on what you are doing with CGo though?

**Comment by aykevl** [comment]
Yeah it's possible that there is some bug in TinyGo that led to this crash. I haven't investigated.

I don't have an ETA but good CGo support is high on my priority list.

**Comment by Chillance** [comment]
Ok, so, I should wait for the CGo support in TinyGo instead then? Also, what will that mean exactly? That will wrap some BLE library then enabling me to do the same as what this was suppose to do (just broadcasting some name) and possibly more?

**Comment by aykevl** [comment]
I don't want to use a library. The SoftDevice is really just a binary blob that can be called using SVCalls. Of course, there are C wrappers for these calls and I'd like to use those.

Unless you want to start hacking on this yourself, you can probably best wait until CGo support has improved to a point that it is usable with the SoftDevice headers. You can see some progress here, where I collect some patches:
https://github.com/tinygo-org/tinygo/pull/98

**Comment by aykevl** [comment]
This should be fixed now.
