### ISSUE TITLE
About GT832c_01

### ISSUE THREAD

**Issue by sonicwasd** [aykevl/things#2]
Hi,

I'm learning about GT832c. Can you give me some suggestion?

My status as follow:

I find the pre-load program on GT832c is heart rate example from SDK?
So, if I want to receive the data from BMI160 and sent it to nrf52832 DK.
Should I have to erase and program nrf52832(GT832c) by myself?
Do you have any idea about this? Or your GT832c can output 3 axis ACC directly

Best Regard

**Comment by aykevl** [comment]
> I find the pre-load program on GT832c is heart rate example from SDK?

I have no idea what program is running on it from the factory, if any. I don't think it will do what you want. I simply erased it and wrote my own.

I think you will need to write your own firmware for it if you want to use it. There are various projects that support this chip, such as [TinyGo](https://tinygo.org/), [MicroPython](https://micropython.org/), and of course [the Arduino IDE](https://github.com/sandeepmistry/arduino-nRF5).

**Comment by sonicwasd** [comment]
Hi,

Thank you.

I already erased the original firmware. And I'm trying write my project.

By the way, have you got any example for this chip?

Ayke <notifications@github.com> 於 2021年2月2日 週二 上午12:20寫道：

**Comment by sonicwasd** [comment]
Hi 你好

請問GT832C_01 這個還有貨嗎?

如果有的話方便能給一下購買的網站嗎?   我有點忘記上次從哪邊聯絡你了







Ayke ***@***.***> 於 2021年2月2日 週二 上午12:20寫道：

**Comment by aykevl** [comment]
I bought these chips on AliExpress, you can search for GT832C_01.

I don't really have any examples for this chip but you can probably use any example for the nrf52 chip.

**Comment by sonicwasd** [comment]
Cool, thanks!

Ayke ***@***.***> 於 2021年6月1日 週二 下午9:23寫道：
